#
#About: This will install Nginx
#
---
- hosts: localhost
  become: yes
  tasks:

    - name: Install nginx
      yum: name=nginx state=present

    - name: insert firewalld rule for nginx
      firewalld: port=80/tcp permanent=true state=enabled immediate=yes
      ignore_errors: yes

    - name: http service state
      service: name=nginx state=started enabled=yes
